### ISSUE TITLE
publishing to npm

### ISSUE THREAD

**Issue by mmautner** [nylas/inbox.js#53]
I see the notice about this SDK no longer being actively managed--but why not ever publish this to npm?

**Comment by spang** [comment]
inbox.js isn't a node module, which is why we didn't publish it to npm. Is there some way it would be useful to you to have it there?

**Comment by mmautner** [comment]
I may be mistaken, but since there's a package.json file present this code is distributable via npm--it doesn't have to be a node/commonjs module.

I ask because we're looking at which vendored code we can pull in from package repositories like npm/bower/etc. during our build/deploy process.

Great talks at PyCon btw!

**Comment by bengotow** [comment]
Hi there! inbox.js is intended to be a client-side javascript SDK for use with Angular / React, etc. It uses XHR requests, assumes a `window` object is present, etc. We could definitely distribute it with `bower`, but we haven't been actively maintaining it since most people are interested in the server-side NodeJS SDK, which you can find over here:

https://github.com/nylas/nylas-nodejs

Sorry for the super confusing naming—I'll see if we can make the difference more clear or potentially merge these together in the future.

**Comment by mmautner** [comment]
No problem, this wasn't really an "issue", just figured it was a good spot to ask the question publicly.
